/* Auto-generated by scripts/optimize-images.mjs — do not edit by hand */
export const IMAGE_MANIFEST = {
  "hero-1": {
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoYABAAPzmGuVOvKSWisAgB4CcJYwDCu/79ysBuqKsaNTpJeAAA/nQdiFRirrPWGiG0EDlUOc8b9hVsnRLqiy/tcoSp1SIpQqbE+Pa+Dh8W6i2nABleQeURTsnmXFkJ3rqyvpvvvbYIDX1GrIKoxSEiQuNM8Y54AOIAAA==",
    "variants": [
      {
        "width": 768,
        "webp": "/images/optimized/hero-1-768.webp",
        "jpg": "/images/optimized/hero-1-768.jpg",
        "webpKb": 54,
        "jpgKb": 64
      },
      {
        "width": 1280,
        "webp": "/images/optimized/hero-1-1280.webp",
        "jpg": "/images/optimized/hero-1-1280.jpg",
        "webpKb": 112,
        "jpgKb": 146
      },
      {
        "width": 1920,
        "webp": "/images/optimized/hero-1-1920.webp",
        "jpg": "/images/optimized/hero-1-1920.jpg",
        "webpKb": 196,
        "jpgKb": 277
      }
    ]
  },
  "hero-2": {
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBACdASoYABAAPzmEuVOvKKWisAgB4CcJbACdMoMggEwrULpGRrpTBQmcomAA/o+qdjuklgzG8sq7R7qMXxhBz/RWMtl8fpU3HGjZ6YgM5IbCHA1CqTEJ1ZHukk7ypWK4pm9mI9PyvDd7wmS852IIRKedMID20CNj4T765D/KFzvayvkuwWxBFgNVBylH3cZ6Un8papxgK4MkkcU5x35JmG0b6ZePqT8ZTFkpCtB4AAAA",
    "variants": [
      {
        "width": 768,
        "webp": "/images/optimized/hero-2-768.webp",
        "jpg": "/images/optimized/hero-2-768.jpg",
        "webpKb": 55,
        "jpgKb": 68
      },
      {
        "width": 1280,
        "webp": "/images/optimized/hero-2-1280.webp",
        "jpg": "/images/optimized/hero-2-1280.jpg",
        "webpKb": 107,
        "jpgKb": 144
      },
      {
        "width": 1920,
        "webp": "/images/optimized/hero-2-1920.webp",
        "jpg": "/images/optimized/hero-2-1920.jpg",
        "webpKb": 175,
        "jpgKb": 257
      }
    ]
  },
  "hero-3": {
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoYABAAPzmGuVOvKSWisAgB4CcJagC+SBsUJtxUmlnvgAD+kSol2V9bAfUSEuHu0BgZ+dvs9F9u9S5XDFLpCdFauJC2fnw3GEK5ySVVi48kRiE19MsSTflesKwWGdIzXJvk/uo3pfSJjTz+79jx+cO9kJ09Wec13+eNhdMBXTevgaYA",
    "variants": [
      {
        "width": 768,
        "webp": "/images/optimized/hero-3-768.webp",
        "jpg": "/images/optimized/hero-3-768.jpg",
        "webpKb": 54,
        "jpgKb": 59
      },
      {
        "width": 1280,
        "webp": "/images/optimized/hero-3-1280.webp",
        "jpg": "/images/optimized/hero-3-1280.jpg",
        "webpKb": 124,
        "jpgKb": 143
      },
      {
        "width": 1920,
        "webp": "/images/optimized/hero-3-1920.webp",
        "jpg": "/images/optimized/hero-3-1920.jpg",
        "webpKb": 229,
        "jpgKb": 279
      }
    ]
  },
  "about": {
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBACdASoYABAAPzmEuVOvKKWisAgB4CcJbACdMoMggEwrULpGRrpTBQmcomAA/o+qdjuklgzG8sq7R7qMXxhBz/RWMtl8fpU3HGjZ6YgM5IbCHA1CqTEJ1ZHukk7ypWK4pm9mI9PyvDd7wmS852IIRKedMID20CNj4T765D/KFzvayvkuwWxBFgNVBylH3cZ6Un8papxgK4MkkcU5x35JmG0b6ZePqT8ZTFkpCtB4AAAA",
    "variants": [
      {
        "width": 640,
        "webp": "/images/optimized/about-640.webp",
        "jpg": "/images/optimized/about-640.jpg",
        "webpKb": 46,
        "jpgKb": 56
      },
      {
        "width": 960,
        "webp": "/images/optimized/about-960.webp",
        "jpg": "/images/optimized/about-960.jpg",
        "webpKb": 80,
        "jpgKb": 102
      },
      {
        "width": 1280,
        "webp": "/images/optimized/about-1280.webp",
        "jpg": "/images/optimized/about-1280.jpg",
        "webpKb": 115,
        "jpgKb": 154
      }
    ]
  },
  "gallery-featured": {
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYABAAPzmEuVOvKKWisAgB4CcJQBdgA+7lMDSwq5S6gsQAAPAZfiB8gPk3fPZGTDb3xjt1RL9oxAkBQmNyuSno7QBkTt8u5IVAp93mXgQI9Pk4Z3eK/8Wcufzcrdss5XoDhOw8KwWUG8n3b6xJULDtOuMQioQrtudXgFEAFjHOk6AA",
    "variants": [
      {
        "width": 640,
        "webp": "/images/optimized/gallery-featured-640.webp",
        "jpg": "/images/optimized/gallery-featured-640.jpg",
        "webpKb": 51,
        "jpgKb": 52
      },
      {
        "width": 960,
        "webp": "/images/optimized/gallery-featured-960.webp",
        "jpg": "/images/optimized/gallery-featured-960.jpg",
        "webpKb": 105,
        "jpgKb": 109
      },
      {
        "width": 1400,
        "webp": "/images/optimized/gallery-featured-1400.webp",
        "jpg": "/images/optimized/gallery-featured-1400.jpg",
        "webpKb": 201,
        "jpgKb": 215
      }
    ]
  },
  "gallery-14": {
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoYABAAPzmGuVOvKSWisAgB4CcJagC+SBsUJtxUmlnvgAD+kSol2V9bAfUSEuHu0BgZ+dvs9F9u9S5XDFLpCdFauJC2fnw3GEK5ySVVi48kRiE19MsSTflesKwWGdIzXJvk/uo3pfSJjTz+79jx+cO9kJ09Wec13+eNhdMBXTevgaYA",
    "variants": [
      {
        "width": 640,
        "webp": "/images/optimized/gallery-14-640.webp",
        "jpg": "/images/optimized/gallery-14-640.jpg",
        "webpKb": 39,
        "jpgKb": 43
      },
      {
        "width": 960,
        "webp": "/images/optimized/gallery-14-960.webp",
        "jpg": "/images/optimized/gallery-14-960.jpg",
        "webpKb": 77,
        "jpgKb": 86
      },
      {
        "width": 1400,
        "webp": "/images/optimized/gallery-14-1400.webp",
        "jpg": "/images/optimized/gallery-14-1400.jpg",
        "webpKb": 143,
        "jpgKb": 167
      }
    ]
  }
} as const;
