/**
 * Compress critical site images to responsive WebP (+ optimized JPEG fallbacks).
 * Run: npm run optimize:images
 */
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const outDir = path.join(root, "public", "images", "optimized");

const JOBS = [
  {
    src: "public/images/hero/hero-1.jpg",
    name: "hero-1",
    widths: [768, 1280, 1920],
    quality: 78,
  },
  {
    src: "public/images/hero/hero-2.jpg",
    name: "hero-2",
    widths: [768, 1280, 1920],
    quality: 78,
  },
  {
    src: "public/images/hero/hero-3.jpg",
    name: "hero-3",
    widths: [768, 1280, 1920],
    quality: 78,
  },
  {
    src: "public/images/brand/about.jpg",
    name: "about",
    widths: [640, 960, 1280],
    quality: 80,
  },
  {
    src: "public/images/gallery/featured.jpg",
    name: "gallery-featured",
    widths: [640, 960, 1400],
    quality: 78,
  },
  {
    src: "public/images/gallery/image-14.jpg",
    name: "gallery-14",
    widths: [640, 960, 1400],
    quality: 78,
  },
];

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function optimizeOne(job) {
  const input = path.join(root, job.src);
  const meta = await sharp(input).metadata();
  const results = [];

  for (const width of job.widths) {
    const targetW = Math.min(width, meta.width ?? width);
    const base = `${job.name}-${targetW}`;

    const webpPath = path.join(outDir, `${base}.webp`);
    const jpgPath = path.join(outDir, `${base}.jpg`);

    await sharp(input)
      .rotate()
      .resize({ width: targetW, withoutEnlargement: true })
      .webp({ quality: job.quality, effort: 6 })
      .toFile(webpPath);

    await sharp(input)
      .rotate()
      .resize({ width: targetW, withoutEnlargement: true })
      .jpeg({ quality: job.quality, mozjpeg: true })
      .toFile(jpgPath);

    const webpStat = await fs.stat(webpPath);
    const jpgStat = await fs.stat(jpgPath);
    results.push({
      width: targetW,
      webp: `/images/optimized/${base}.webp`,
      jpg: `/images/optimized/${base}.jpg`,
      webpKb: Math.round(webpStat.size / 1024),
      jpgKb: Math.round(jpgStat.size / 1024),
    });
  }

  // Tiny LQIP blur placeholder (inline-friendly size)
  const lqipBuf = await sharp(input)
    .rotate()
    .resize({ width: 24 })
    .webp({ quality: 20 })
    .toBuffer();
  const lqip = `data:image/webp;base64,${lqipBuf.toString("base64")}`;

  return { name: job.name, variants: results, lqip };
}

await ensureDir(outDir);

const manifest = {};
for (const job of JOBS) {
  console.log(`Optimizing ${job.src}...`);
  const result = await optimizeOne(job);
  manifest[result.name] = {
    lqip: result.lqip,
    variants: result.variants,
  };
  for (const v of result.variants) {
    console.log(
      `  ${v.width}w → webp ${v.webpKb}KB | jpg ${v.jpgKb}KB`,
    );
  }
}

const manifestPath = path.join(root, "src", "lib", "image-manifest.ts");
const file = `/* Auto-generated by scripts/optimize-images.mjs — do not edit by hand */
export const IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;
`;
await fs.writeFile(manifestPath, file, "utf8");
console.log(`\nWrote ${path.relative(root, manifestPath)}`);
